## Case Study: How Can a Wellness Technology Company Play It Smart?

[Case Study description](#1)   
[Business Task](#2)  
[1. Ask](#3)  
[2. Prepare](#4)  
[3. Process](#5)  
[4. Analyze](#6)  
[5. Share](#7)  
[6. Act](#8)  

<a id="1"></a> <br>
###  Case Study description

Bellabeat is a high-tech manufacturer of health-focused products for women. Collecting data on activity, sleep, stress, and reproductive health empowers women with knowledge about their own health and habits. Since it was founded in 2013, Bellabeat has grown rapidly and quickly positioned itself as a tech-driven wellness company for women.

The purpose of the case study is to analyze smart device fitness data to gain insight into how consumers use their smart devices. The insights will help unlock new growth opportunities for the company.
 

<a id="2"></a> <br>
### Business Task

Analyze data from the FitBit fitness tracker to see how users interact with the FitBit app and determine trends to guide marketing strategy for the company. 

<a id="3"></a> <br>
### 1. Ask

The first step in the data analysis process is to ask the right questions. 

Who are the main stakeholders in this project and what are their expectations? 

The following stakeholders are involved in this project: 
*  Urška Sršen: Bellabeat’s cofounder and Chief Creative Officer
*  Sando Mur: Mathematician and Bellabeat’s cofounder; key member of the Bellabeat executive team
*  Bellabeat marketing analytics team: A team of data analysts responsible for collecting, analyzing, and reporting data that helps guide Bellabeat’s marketing strategy.

What is the problem you are trying to solve?
How can your insights drive business decisions?

Bellabeat is a successful small company, but they have the potential to become a larger player in the global smart device market. Analyzing fitness smart device will help to unlock new growth opportunities for the company.
Identified trends will help to draw up high-level recommendations for Bellabeat’s marketing strategy. 

 **Key questions:**
1. What are some of the trends in smart device usage?
2. How could these trends apply to Bellabeat customers?
3. How could these trends help influence Bellabeat marketing strategy?

<a id="4"></a> <br>
### 2. Prepare


The data used for the project is freely accessible public data from Kaggle generated by responders to a distributed survey via Amazon Mechanical Turk between 03.12.2016-05.12.2016. This Kaggle data set  [FitBit Fitness Tracker Data ](https://www.kaggle.com/datasets/arashnic/fitbit)contains personal fitness tracker from thirty Fitbit users who signed the consent to share the personal tracker data, including daily activity, steps, and heart rate. 
The data is stored in 18 csv files and organized in wide format.


**Data integrity and credibility**

This data has limitations. The data was collected in 2016, seven years ago, and may not be actual and accurate. Since then, people's behavior, physical activity, diet, sleeping and health habits may change.  Seven years is also a significant period in scientific and technological progress (today devices can work two or three weeks without recharging, mobility and almost imperceptibility on the hand, a widget for quick synchronization etc.) which could also change usage habits. 

Number of participants may not be representative of the general female population.

It is important to also consider other factors such as age, overall physical activity, diet, family history, and other health conditions when assessing an individual's overall health status. Consulting with a healthcare provider can help provide personalized recommendations for improving health and managing any potential health risks.

The integrity and validity of the data are incomplete to provide Bellabeat with reliable insights and business suggestions. Thus, the following analysis can only give the first ideas and directions, which need to be verified by analyzing more extensive and up-to-date data.


**ROCCC system to determine that data is Reliable, Original, Comprehensive, Current, and Cited.**


* Reliable — LOW — 30 responders are a small sample size and does not accurately reflect the entire population of female Fitbit users. 
* Original — LOW — Amazon Mechanical Turk is Third party data provider.
* Comprehensive — LOW — The dataset does not consist of data about gender, age, health conditions and it is not random. The data is biased against women. Low accuracy does not represent the case objectively.
* Current — LOW — 7-year-old data is not present
* Cited — LOW — Data obtained from an unidentified third party (Amazon Mechanical Murk)

<a id="5"></a> <br>
###  3. Process

The following analysis will be focused on three datasets: "dailyActivity_merged" "sleepDay_merged", "weightLogInfo_merged.csv" to identify trends in user data.
​
The processes of data cleaning, manipulation, analysis, and visualization will be performed in RStudio. 

In [10]:
## Setting up my R environment by loading packages and libraries
install.packages("tidyverse")
install.packages("skimr")
install.packages("here")
install.packages("janitor")
install.packages("ggplot2") 
install.packages("lubridate")
install.packages("dplyr")             
install.packages("sqldf")
install.packages("plotrix")

library(tidyverse)
library(skimr)
library(here)
library(janitor)
library(ggplot2)  
library(lubridate)
library(dplyr)              
library(sqldf)
library(plotrix)


The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages are in
	/var/folders/_x/0l04gg0n0_z9ysm2n2g6kxjc0000gn/T//RtmpkZTWHx/downloaded_packages

The downloaded binary packages 

ERROR: Error: package or namespace load failed for ‘skimr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘pillar’ 1.8.1 is already loaded, but >= 1.9.0 is required


In [3]:
##Importing data files in R
daily_activity <- read.csv("dailyActivity_merged.csv")
sleep_day <- read.csv("sleepDay_merged.csv")
weight_info_log <- read.csv("weightLogInfo_merged.csv")

Let's Take a closer look at each dataset:

In [4]:
##Invoke a spreadsheet-style data viewer within RStudio
View(daily_activity)
View(sleep_day)
View(weight_info_log)

##Take a closer look at each dataset 
head(daily_activity)
head(sleep_day)
head(weight_info_log)

##Display columns and dataset structure 
str(daily_activity)
str(sleep_day)
str(weight_info_log)


Id         ActivityDate TotalSteps TotalDistance TrackerDistance
1   1503960366 4/12/2016    13162       8.50          8.50          
2   1503960366 4/13/2016    10735       6.97          6.97          
3   1503960366 4/14/2016    10460       6.74          6.74          
4   1503960366 4/15/2016     9762       6.28          6.28          
5   1503960366 4/16/2016    12669       8.16          8.16          
6   1503960366 4/17/2016     9705       6.48          6.48          
7   1503960366 4/18/2016    13019       8.59          8.59          
8   1503960366 4/19/2016    15506       9.88          9.88          
9   1503960366 4/20/2016    10544       6.68          6.68          
10  1503960366 4/21/2016     9819       6.34          6.34          
11  1503960366 4/22/2016    12764       8.13          8.13          
12  1503960366 4/23/2016    14371       9.04          9.04          
13  1503960366 4/24/2016    10039       6.41          6.41          
14  1503960366 4/25/2016    15355       9.80          9.80          
15  1503960366 4/26/2016    13755       8.79          8.79          
16  1503960366 4/27/2016    18134      12.21         12.21          
17  1503960366 4/28/2016    13154       8.53          8.53          
18  1503960366 4/29/2016    11181       7.15          7.15          
19  1503960366 4/30/2016    14673       9.25          9.25          
20  1503960366 5/1/2016     10602       6.81          6.81          
21  1503960366 5/2/2016     14727       9.71          9.71          
22  1503960366 5/3/2016     15103       9.66          9.66          
23  1503960366 5/4/2016     11100       7.15          7.15          
24  1503960366 5/5/2016     14070       8.90          8.90          
25  1503960366 5/6/2016     12159       8.03          8.03          
26  1503960366 5/7/2016     11992       7.71          7.71          
27  1503960366 5/8/2016     10060       6.58          6.58          
28  1503960366 5/9/2016     12022       7.72          7.72          
29  1503960366 5/10/2016    12207       7.77          7.77          
30  1503960366 5/11/2016    12770       8.13          8.13          
⋮   ⋮          ⋮            ⋮          ⋮             ⋮              
911 8877689391 4/13/2016    15337       9.58          9.58          
912 8877689391 4/14/2016    21129      18.98         18.98          
913 8877689391 4/15/2016    13422       7.17          7.17          
914 8877689391 4/16/2016    29326      25.29         25.29          
915 8877689391 4/17/2016    15118       8.87          8.87          
916 8877689391 4/18/2016    11423       8.67          8.67          
917 8877689391 4/19/2016    18785      17.40         17.40          
918 8877689391 4/20/2016    19948      18.11         18.11          
919 8877689391 4/21/2016    19377      17.62         17.62          
920 8877689391 4/22/2016    18258      16.31         16.31          
921 8877689391 4/23/2016    11200       7.43          7.43          
922 8877689391 4/24/2016    16674      15.74         15.74          
923 8877689391 4/25/2016    12986       8.74          8.74          
924 8877689391 4/26/2016    11101       8.43          8.43          
925 8877689391 4/27/2016    23629      20.65         20.65          
926 8877689391 4/28/2016    14890      11.30         11.30          
927 8877689391 4/29/2016     9733       7.39          7.39          
928 8877689391 4/30/2016    27745      26.72         26.72          
929 8877689391 5/1/2016     10930       8.32          8.32          
930 8877689391 5/2/2016      4790       3.64          3.64          
931 8877689391 5/3/2016     10818       8.21          8.21          
932 8877689391 5/4/2016     18193      16.30         16.30          
933 8877689391 5/5/2016     14055      10.67         10.67          
934 8877689391 5/6/2016     21727      19.34         19.34          
935 8877689391 5/7/2016     12332       8.13          8.13          
936 8877689391 5/8/2016     10686       8.11          8.11          
93

Id         SleepDay              TotalSleepRecords TotalMinutesAsleep
1   1503960366 4/12/2016 12:00:00 AM 1                 327               
2   1503960366 4/13/2016 12:00:00 AM 2                 384               
3   1503960366 4/15/2016 12:00:00 AM 1                 412               
4   1503960366 4/16/2016 12:00:00 AM 2                 340               
5   1503960366 4/17/2016 12:00:00 AM 1                 700               
6   1503960366 4/19/2016 12:00:00 AM 1                 304               
7   1503960366 4/20/2016 12:00:00 AM 1                 360               
8   1503960366 4/21/2016 12:00:00 AM 1                 325               
9   1503960366 4/23/2016 12:00:00 AM 1                 361               
10  1503960366 4/24/2016 12:00:00 AM 1                 430               
11  1503960366 4/25/2016 12:00:00 AM 1                 277               
12  1503960366 4/26/2016 12:00:00 AM 1                 245               
13  1503960366 4/28/2016 12:00:00 AM 1                 366               
14  1503960366 4/29/2016 12:00:00 AM 1                 341               
15  1503960366 4/30/2016 12:00:00 AM 1                 404               
16  1503960366 5/1/2016 12:00:00 AM  1                 369               
17  1503960366 5/2/2016 12:00:00 AM  1                 277               
18  1503960366 5/3/2016 12:00:00 AM  1                 273               
19  1503960366 5/5/2016 12:00:00 AM  1                 247               
20  1503960366 5/6/2016 12:00:00 AM  1                 334               
21  1503960366 5/7/2016 12:00:00 AM  1                 331               
22  1503960366 5/8/2016 12:00:00 AM  1                 594               
23  1503960366 5/9/2016 12:00:00 AM  1                 338               
24  1503960366 5/10/2016 12:00:00 AM 1                 383               
25  1503960366 5/11/2016 12:00:00 AM 1                 285               
26  1644430081 4/29/2016 12:00:00 AM 1                 119               
27  1644430081 4/30/2016 12:00:00 AM 1                 124               
28  1644430081 5/2/2016 12:00:00 AM  1                 796               
29  1644430081 5/8/2016 12:00:00 AM  1                 137               
30  1844505072 4/15/2016 12:00:00 AM 1                 644               
⋮   ⋮          ⋮                     ⋮                 ⋮                 
384 8378563200 4/28/2016 12:00:00 AM 1                 506               
385 8378563200 4/29/2016 12:00:00 AM 1                 527               
386 8378563200 4/30/2016 12:00:00 AM 1                 468               
387 8378563200 5/1/2016 12:00:00 AM  1                 475               
388 8378563200 5/2/2016 12:00:00 AM  1                 351               
389 8378563200 5/3/2016 12:00:00 AM  1                 405               
390 8378563200 5/4/2016 12:00:00 AM  1                 441               
391 8378563200 5/5/2016 12:00:00 AM  1                 381               
392 8378563200 5/6/2016 12:00:00 AM  1                 323               
393 8378563200 5/7/2016 12:00:00 AM  2                 459               
394 8378563200 5/8/2016 12:00:00 AM  1                 545               
395 8378563200 5/9/2016 12:00:00 AM  1                 359               
396 8378563200 5/10/2016 12:00:00 AM 1                 342               
397 8378563200 5/11/2016 12:00:00 AM 1                 368               
398 8378563200 5/12/2016 12:00:00 AM 1                 496               
399 8792009665 4/12/2016 12:00:00 AM 1                 458               
400 8792009665 4/13/2016 12:00:00 AM 1                 531               
401 8792009665 4/14/2016 12:00:00 AM 1                 486               
402 8792009665 4/15/2016 12:00:00 AM 1                 363               
403 8792009665 4/20/2016 12:00:00 AM 1                 528               
404 8792009665 4/22/2016 12:00:00 AM 1                 391               
405 8792009665 4/23/2016 12:00:00 AM 1                 339               
406 8792

Id         Date                  WeightKg WeightPounds Fat BMI  
1  1503960366 5/2/2016 11:59:59 PM   52.6    115.9631     22  22.65
2  1503960366 5/3/2016 11:59:59 PM   52.6    115.9631     NA  22.65
3  1927972279 4/13/2016 1:08:52 AM  133.5    294.3171     NA  47.54
4  2873212765 4/21/2016 11:59:59 PM  56.7    125.0021     NA  21.45
5  2873212765 5/12/2016 11:59:59 PM  57.3    126.3249     NA  21.69
6  4319703577 4/17/2016 11:59:59 PM  72.4    159.6147     25  27.45
7  4319703577 5/4/2016 11:59:59 PM   72.3    159.3942     NA  27.38
8  4558609924 4/18/2016 11:59:59 PM  69.7    153.6622     NA  27.25
9  4558609924 4/25/2016 11:59:59 PM  70.3    154.9850     NA  27.46
10 4558609924 5/1/2016 11:59:59 PM   69.9    154.1031     NA  27.32
11 4558609924 5/2/2016 11:59:59 PM   69.2    152.5599     NA  27.04
12 4558609924 5/9/2016 11:59:59 PM   69.1    152.3394     NA  27.00
13 5577150313 4/17/2016 9:17:55 AM   90.7    199.9593     NA  28.00
14 6962181067 4/12/2016 11:59:59 PM  62.5    137.7889     NA  24.39
15 6962181067 4/13/2016 11:59:59 PM  62.1    136.9071     NA  24.24
16 6962181067 4/14/2016 11:59:59 PM  61.7    136.0252     NA  24.10
17 6962181067 4/15/2016 11:59:59 PM  61.5    135.5843     NA  24.00
18 6962181067 4/16/2016 11:59:59 PM  62.0    136.6866     NA  24.21
19 6962181067 4/17/2016 11:59:59 PM  61.4    135.3638     NA  23.96
20 6962181067 4/18/2016 11:59:59 PM  61.2    134.9229     NA  23.89
21 6962181067 4/19/2016 11:59:59 PM  61.4    135.3638     NA  23.96
22 6962181067 4/20/2016 11:59:59 PM  61.7    136.0252     NA  24.10
23 6962181067 4/21/2016 11:59:59 PM  61.4    135.3638     NA  23.96
24 6962181067 4/22/2016 11:59:59 PM  61.4    135.3638     NA  23.96
25 6962181067 4/23/2016 11:59:59 PM  61.5    135.5843     NA  24.00
26 6962181067 4/24/2016 11:59:59 PM  61.5    135.5843     NA  24.00
27 6962181067 4/25/2016 11:59:59 PM  61.7    136.0252     NA  24.10
28 6962181067 4/27/2016 11:59:59 PM  61.2    134.9229     NA  23.89
29 6962181067 4/28/2016 11:59:59 PM  61.2    134.9229     NA  23.89
30 6962181067 4/29/2016 11:59:59 PM  61.4    135.3638     NA  23.96
⋮  ⋮          ⋮                     ⋮        ⋮            ⋮   ⋮    
38 6962181067 5/7/2016 11:59:59 PM  61.2     134.9229     NA  23.89
39 6962181067 5/8/2016 11:59:59 PM  61.2     134.9229     NA  23.89
40 6962181067 5/9/2016 11:59:59 PM  62.4     137.5685     NA  24.35
41 6962181067 5/10/2016 11:59:59 PM 62.1     136.9071     NA  24.24
42 6962181067 5/11/2016 11:59:59 PM 61.9     136.4661     NA  24.17
43 6962181067 5/12/2016 11:59:59 PM 61.9     136.4661     NA  24.17
44 8877689391 4/12/2016 6:47:11 AM  85.8     189.1566     NA  25.68
45 8877689391 4/13/2016 6:55:00 AM  84.9     187.1725     NA  25.41
46 8877689391 4/14/2016 6:48:43 AM  84.5     186.2906     NA  25.31
47 8877689391 4/16/2016 1:39:25 PM  85.5     188.4952     NA  25.59
48 8877689391 4/18/2016 6:51:14 AM  85.8     189.1566     NA  25.68
49 8877689391 4/19/2016 6:39:31 AM  85.3     188.0543     NA  25.53
50 8877689391 4/20/2016 6:44:54 AM  84.9     187.1725     NA  25.41
51 8877689391 4/21/2016 6:50:27 AM  84.5     186.2906     NA  25.29
52 8877689391 4/23/2016 7:22:28 AM  85.5     188.4952     NA  25.59
53 8877689391 4/24/2016 7:38:05 AM  85.5     188.4952     NA  25.59
54 8877689391 4/25/2016 6:40:16 AM  85.4     188.2748     NA  25.56
55 8877689391 4/26/2016 6:50:27 AM  85.1     187.6134     NA  25.49
56 8877689391 4/27/2016 6:51:05 AM  85.4     188.2748     NA  25.56
57 8877689391 4/28/2016 6:50:03 AM  85.1     187.6134     NA  25.49
58 8877689391 4/29/2016 6:49:55 AM  84.9     187.1725     NA  25.41
59 8877689391 4/30/2016 7:49:03 AM  85.5     188.4952     NA  25.59
60 8877689391 5/1/2016 8:47:49 AM   85.3     188.0543     NA  25.53
61 8877689391 5/3/2016 6:49:41 AM   84.9     187.1725     NA  25.41
62 8877689391 5/4/2016 6:48:22 AM   84.4     186.0702     NA  25.26
63 8877689391 5/6/2016 6:43:35 AM   85.0     187.3929     NA  25.44
64 8877689391 5/8/2016 7:35:53 AM   85.4     188.2748     N

Id         ActivityDate TotalSteps TotalDistance TrackerDistance
1 1503960366 4/12/2016    13162      8.50          8.50           
2 1503960366 4/13/2016    10735      6.97          6.97           
3 1503960366 4/14/2016    10460      6.74          6.74           
4 1503960366 4/15/2016     9762      6.28          6.28           
5 1503960366 4/16/2016    12669      8.16          8.16           
6 1503960366 4/17/2016     9705      6.48          6.48           
  LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
1 0                        1.88               0.55                    
2 0                        1.57               0.69                    
3 0                        2.44               0.40                    
4 0                        2.14               1.26                    
5 0                        2.71               0.41                    
6 0                        3.19               0.78                    
  LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
1 6.06                0                       25               
2 4.71                0                       21               
3 3.91                0                       30               
4 2.83                0                       29               
5 5.04                0                       36               
6 2.51                0                       38               
  FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
1 13                  328                   728             1985    
2 19                  217                   776             1797    
3 11                  181                  1218             1776    
4 34                  209                   726             1745    
5 10                  221                   773             1863    
6 20                  164                   539             1728

Id         SleepDay              TotalSleepRecords TotalMinutesAsleep
1 1503960366 4/12/2016 12:00:00 AM 1                 327               
2 1503960366 4/13/2016 12:00:00 AM 2                 384               
3 1503960366 4/15/2016 12:00:00 AM 1                 412               
4 1503960366 4/16/2016 12:00:00 AM 2                 340               
5 1503960366 4/17/2016 12:00:00 AM 1                 700               
6 1503960366 4/19/2016 12:00:00 AM 1                 304               
  TotalTimeInBed
1 346           
2 407           
3 442           
4 367           
5 712           
6 320

Id         Date                  WeightKg WeightPounds Fat BMI  
1 1503960366 5/2/2016 11:59:59 PM   52.6    115.9631     22  22.65
2 1503960366 5/3/2016 11:59:59 PM   52.6    115.9631     NA  22.65
3 1927972279 4/13/2016 1:08:52 AM  133.5    294.3171     NA  47.54
4 2873212765 4/21/2016 11:59:59 PM  56.7    125.0021     NA  21.45
5 2873212765 5/12/2016 11:59:59 PM  57.3    126.3249     NA  21.69
6 4319703577 4/17/2016 11:59:59 PM  72.4    159.6147     25  27.45
  IsManualReport LogId       
1 True           1.462234e+12
2 True           1.462320e+12
3 False          1.460510e+12
4 True           1.461283e+12
5 True           1.463098e+12
6 True           1.460938e+12

'data.frame':	940 obs. of  15 variables:
 $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityDate            : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
 $ TotalSteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
 $ TotalDistance           : num  8.5 6.97 6.74 6.28 8.16 ...
 $ TrackerDistance         : num  8.5 6.97 6.74 6.28 8.16 ...
 $ LoggedActivitiesDistance: num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...
 $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
 $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
 $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
 $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
 $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
 $ SedentaryMinutes        : int  728 776 1218 726 773 539 

**Cleaning data**  
Before the analysis the data must be checked  for duplicates, misspellings, missing values, errors.

weight_info data frame has missing values. To show just records with filled values we can remove the whole column “Fat” as there is no information for the insights or we can display all columns without “Fat” column.

In [8]:
#Fixing N/A values in the weight_info dataframe
weight_info <- weight_info_log %>% 
  select(Id, Date, WeightKg, WeightPounds, BMI, IsManualReport, LogId)
View(weight_info)

ERROR: Error in weight_info_log %>% select(Id, Date, WeightKg, WeightPounds, : could not find function "%>%"


In [7]:
#Counting number of rows in each dataset 
nrow(daily_activity)
nrow(sleep_day)
nrow(weight_info)

[1] 940

[1] 413

ERROR: Error in nrow(weight_info): object 'weight_info' not found


There are 940 rows in the daily_activity dataset, 413 rows in the sleep_day and 67 rows in the weight_info dataset

In [ ]:
#Checking for duplicate rows
nrow(daily_activity[duplicated(daily_activity),])
nrow(sleep_day[duplicated(sleep_day),])
nrow(weight_info[duplicated(weight_info),])


From this there are 3 duplicate rows found in the sleep_day dataset. Let's remove them. 

In [ ]:
#Removing duplicate rows 
sleep_day <- unique(sleep_day)
nrow(sleep_day)

For sleep_day and weight_info dataframes we will use separte() function to split date and time into separate columns. 

In [ ]:
#Using separate() function function to split date and time into separate columns in the sleep_day and weight_info dataframes
sleep_day_new <- sleep_day %>% 
  separate(SleepDay, c("Date", "Time"), " ")
View(sleep_day_new)

weight_info_new <- weight_info %>%
  separate(Date, c("Date", "Time"), " ")
View(weight_info_new)  


Change data type from char to date format in each dataframe for the future analysis and check how data type changed. 

In [ ]:
#Change data type from char to date format
daily_activity$ActivityDate = as.Date(daily_activity$ActivityDate, "%m/%d/%Y") 
View(daily_activity)

sleep_day_new$Date = as.Date(sleep_day_new$Date, "%m/%d/%Y") 
View(sleep_day_new)

weight_info_new$Date = as.Date(weight_info_new$Date,"%m/%d/%Y") 
View(weight_info_new)


#Check how data type changed
glimpse(daily_activity)
glimpse(sleep_day_new)
glimpse(weight_info_new)


Define the number of unique users by id with n_distinct() function



In [ ]:
#Define the number of unique rows by Id column
n_distinct(daily_activity$Id)
n_distinct(sleep_day_new$Id)
n_distinct(weight_info_new$Id)

From this we defined that there are: 33 unique responders in the daily_activity  dataframe, 24 unique responders in the sleep_day_new  and only 8 unique responders in the weight_info_new dataframe.

<a id="6"></a> <br>
###  4. Analyze

The best way to represent a set of numbers and see the central trend of the entire data set is to find the central value, the mean using summary() function. 

In [ ]:
# daily_activity dataset summary 
daily_activity %>% 
  select(TotalSteps,
         TotalDistance,
         VeryActiveMinutes,
         FairlyActiveMinutes,
         LightlyActiveMinutes,
         SedentaryMinutes,
         Calories) %>% 
  summary()

#sleep_day_new dataframe summary

sleep_day_new %>% 
  select(TotalSleepRecords,
         TotalMinutesAsleep,
         TotalTimeInBed) %>% 
  summary() 

#weight_info_new dataframe summary

weight_info %>% 
  select(WeightKg,
         WeightPounds,
         BMI) %>%  
  summary()


**Observations and conclusions for each dataset based on the summary**  

**Daily Activity dataset**  

Observations:  

- An average user walks 5.490 km or 7638 steps a day. The CDC recommend that most adults aim for 10,000 steps per day. For most people, this is the equivalent of about 8 kilometers, or 5 miles.
- An average user spends 991.2 minutes or 16.52 hours in 24-hour movement sedentarily. A little physical movement while awake, up to 10 hours a day without movement, can increase the risk of chronic diseases, including high cholesterol, blood pressure. Adults are advised to limit sedentary time to 8 hours or less.

- The average calories burned daily are 2304 kCal. The appropriate number of calories burned per day varies depending on factors such as age, gender, weight, height, and activity level.

- The average of highly active minutes spent is 21.16 minutes, which is less then at least 30 minutes per day exercising intentionally. 
 
Conclusions:  

- Responders are sedentary throughout the day in general
- Responders spend their time mostly inactive rather than very active or active.
- Responders spend a small amount of time doing exercises.


**Sleep Per Day:**  

Observations:  

- The average number total sleep time is 419 minutes, or around 7 hours.
- The average time spent in bed is 458 minutes or 7 hours 30 min.
- Users record sleep at least once a daily in average

Conclusions:  

- Responders in average spent 30 minutes in bed awake 
- Participants get enough sleep on average
- Most of participants sleep once per day 


**Weight Log Info Dataset:**  

Observations:  

- The average BMI is 25.19, which is significantly higher than normal 
       BMI range (18 – 24.9).
- The average weight is 72 kg, or 158.8 pounds.

There are only 8 responders shared their weight data. There is no data on users' age, height, or body fat percentage to draw conclusions about health.

Conclusions:    

- None of the participants are underweight
- The average height of responders is 169 cm 
- According to the CDC, a person with a BMI between 25 and 29.9 is considered overweight.


<a id="7"></a> <br>
### 5. Share

**Identifying trends and relationships**  


**Frequency of use of the FitBit during the week**  

I used Google spreadsheet tool to define the day of week for each day in ActivityDay column. 

 =switch(WEEKDAY(B2),1,"Sunday",2,"Monday",3,"Tuesday",4,
"Wednesday",5, "Thursday",6,"Friday",7,"Saturday")

Now we can count how many times each day of the week appeared in the table, and based on this information, create a bar chart showing the percentage of FitBit usage during the week.

=COUNTIF(C:C, "Monday")



According to the bar chart people are more active on Tuesday, Wednesday, and Thursday. Tuesday is the most popular day of the week to work out.
In the middle of the week, people have the highest motivation for activity.
On Monday an average person goes through the day's activities lacking motivation and productivity that’s why the percentage is the lowest - 12.8 %. 

**Relationship between sleep and sedentary time**

In [ ]:
#Determining the correlation between sleep and sedentary time
#Merge two dataframes: daily_activity, sleep_day_new, using composite key.

sleep_sedentary_correlation <- merge(daily_activity, sleep_day_new, by.x = c("Id", "ActivityDate"), by.y = c("Id", "Date"))
sleep_sedentary_cor <- subset(sleep_sedentary_correlation, select = c("Id", "ActivityDate", "TotalTimeInBed", "TotalMinutesAsleep", "SedentaryMinutes"))

View(sleep_sedentary_cor)


In [ ]:
ggplot(data= sleep_sedentary_cor, aes(x=SedentaryMinutes, y=TotalMinutesAsleep)) + 
  geom_point(colour="Chocolate1") + geom_smooth(color = "cadetblue4")+
  labs(title="Correlation Between Sedentary Time and Time Asleep", x="Sedentary Time (minutes)", y="Time Asleep (minutes)")


The scatter plot above shows that between 0- 1500 sedentary minutes total time asleep decreases with increasing sedentary time.

In [ ]:
#calculate the correlation index between sedentary time and time asleep
cor(sleep_sedentary_cor$SedentaryMinutes, sleep_sedentary_cor$TotalMinutesAsleep)


Value of -0.6 indicating a negative correlation (one variable increases as the other decreases) between total time asleep and sedatives minutes.

**Correlation between total steps and calories burned**

In [ ]:
#Determining the correlation between total steps and calories 

ggplot(data= daily_activity, aes(x=TotalSteps, y=Calories)) + 
  geom_point(color="Chocolate1") + 
  geom_smooth(color = "cadetblue4")+
  labs(title="Relationship Between Steps and Calories", x="Steps", y="Calories burned")



According to the scatterplot, there is an obvious positive correlation between the total number of steps and calories: the more steps taken the greater number of calories burned.

**Minutes spent in different activity levels**

In [ ]:
Sedentary <- sum(daily_activity$SedentaryMinutes)
Lightly <- sum(daily_activity $LightlyActiveMinutes)
Fairly <- sum(daily_activity $FairlyActiveMinutes)
Active <- sum(daily_activity $VeryActiveMinutes)

activity_minutes <- c(Sedentary,Lightly, Fairly, Active)

# calculate the percentage of active minutes for each level of activity
activity_percent <- round(activity_minutes/sum(activity_minutes)*100,1)

# create a pie chart showing the percentage of active minutes for each level of activity

legend_labels <- c("Sedentary","Lightly Active", "Fairly Active","Very Active")
pie3D(activity_percent, labels=paste0(activity_percent,"%"), main="Percentage of Active Minutes by Activity Level", col=c("aquamarine3","khaki1", "darkorange3","lightblue"), border="lightgrey", labelcex = 0.9)
legend("topright", legend_labels, cex=0.8, fill=c("aquamarine3","khaki1", "darkorange3","lightblue"))


The pie chart provides a quick and easy-to-read summary of the percentage of minutes spent in different activity levels, which could be helpful for understanding the overall activity patterns of the participants.

The pie chart indicates that sedentary minutes account for a high percentage of all minutes (81.3%), what might be related to Desk jobs (office jobs), screen time (spending more time in front of screens, whether it's for work or leisure), lifestyle habits (reading or watching movies), using cars and other transportations a lot. This can lead to a sedentary lifestyle and can be a major contributor to the high percentage of sedentary minutes

**Sleep time vs Time in bed**



In [ ]:
# Creating a plot 
ggplot(data= sleep_day_new, aes(x= TotalMinutesAsleep, y=TotalTimeInBed)) + 
  geom_point(color="Chocolate3") + 
  geom_smooth(color = "cadetblue4")+
  labs(title="Sleep time vs Time in bed ", x="Time asleep (minutes)", y="Total time in bed (minutes)")


The scatterplot displays a positive correlation between sleep time and time spent in bed. Bellabeat can motivate users to go to bed earlier to get adequate amount of sleep and good quality of sleep. 

 By tracking sleep, users can explore their sleep patterns and make some adjustments to their sleep habits. Going to bed earlier can regulate sleep schedule. As soon as individual “sleep need” is determined, it will be easier to wake up naturally at the right time every morning which will lead to better overall health and well-being.

**Exploring the day with the highest number of minutes asleep**

In [ ]:
# Create new column with day of the week
sleep_day_new$DayOfWeek <- weekdays(sleep_day_new$Date)

# View the updated data frame
View(sleep_day_new)


In [ ]:
#Defining the day with the highest sleeping time

sleep_day_new %>%
  group_by(DayOfWeek) %>%
  summarize(total_minutes_asleep = sum(TotalMinutesAsleep)) %>%
  arrange(desc(total_minutes_asleep)) %>%
  head(1)


In [ ]:
#Create a visual showing the total number of minutes asleep for each day of the week    

sleep_day_new %>%
  group_by(DayOfWeek) %>%
  summarize(total_minutes_asleep = sum(TotalMinutesAsleep)) %>%
  mutate(percent_of_total = round(total_minutes_asleep / sum(total_minutes_asleep) * 100, 1)) %>%
  ggplot(aes(x = DayOfWeek, y = total_minutes_asleep)) +
  geom_col(fill = "cadetblue4") +
  geom_text(aes(label = paste0(percent_of_total, "%")), vjust = -0.5) +
  labs(x = "Day of Week", y = "Total Minutes Asleep", 
       title = "Total Minutes Asleep by Day of Week")



The bar chart shows that Wednesday is the day with the highest total minutes of sleep. This information can be useful in understanding sleep patterns and identifying factors that may affect sleep quality on different days of the week.

<a id="8"></a> <br>
###  6. Act

In the last section of this case study, I will provide observations and suggestions based on the analysis.  
To do this, I will return to key questions.
What are some of the trends in smart device usage?

1) Based on the analysis and calculation of unique users, responders most often use the FitBit to track their daily activity levels and calories burned, fewer people for sleep control and very few report information about weight.

2) User in average spends approximately 16.5 hours in 24-hour movement sedentarily.  

3) Responders spend their time mostly inactive rather than very active or active and spend small amount of time doing exercises.

4) An average user walks 5.5 kilometers a day, this could be considered a moderately active lifestyle. The CDC recommend that most adults aim for 10,000 steps per day. For most people, this is the equivalent of about 8 kilometers, or 5 miles.

5) The average number of total time asleep is approximately 7 hours. This would fall within the range of recommended sleep duration for adults, which is typically 7-9 hours per night.

6) There is a strong negative correlation (-0.6) between total time asleep and sedentary minutes. The longer the sedentary time, the stronger the association with poor sleep quality and duration.

7) Lack of physical activity during the day can lead to increased levels of stress and anxiety, which can make it more difficult to fall asleep at night. Additionally, a sedentary lifestyle can lead to a decrease in overall energy expenditure, which can contribute to feelings of fatigue and daytime sleepiness.

8) An average BMI of 25.19 falls within the overweight range according to the World Health Organization (WHO) classification.  

9) Tuesday is the most popular day for work outs.  

10) There is a strong correlation between total steps taken and calories burned.  

11) Saturday is the day users get the most sleep in a week.


How could trends apply to Bellabeat customers?
How could these trends help influence Bellabeat marketing strategy?

By leveraging trends and focusing on the unique needs and behaviors users, Bellabeat could tailor its marketing strategy to better meet the needs of its target audience and help them achieve their fitness and wellness goals.

1) Promote active lifestyle: Given that users spend a significant amount of time sedentary and are not very active, Bellabeat could focus on promoting the benefits of an active lifestyle.   

2) Incorporating some of the features that can be a great way to encourage more physical activity and walking:  

- goal setting (target to encourage users to aim for 10,000 steps per day or more), receiving reminders throughout the day to reach those goals

- gamification elements, such as challenges or rewards, reminders, or alerts throughout the day to encourage them to take breaks from sedentary activities.  

- coaching and feedback features that can provide users with personalized recommendations for how to improve their activity levels.  

3) For improving the weight control experience successful marketing strategy should focus on promoting weight management features, such as calorie tracking and meal planning to help users achieve a healthy weight:  

- integration of a food diary: Bellabeat could partner with popular food tracking apps or create its own in-app diary to track and monitor food intake in addition to their physical activity for a comprehensive picture of overall calorie balance.  
 
- utilize personalized recommendations for healthy eating and exercise habits (suggest specific meal plans based on the user's dietary preferences or suggest targeted exercises to help meet specific weight loss goals). 

- Integrate community support: social features to allow users to connect with each other and offer support and motivation. This may include virtual challenges or competitions that encourage users to work towards a common goal or simply a platform for users to share their progress. 

- offer additional resources such as nutrition and fitness guides or access to certified dietitians or personal trainers. This can provide users with additional support and guidance to help them achieve their weight loss goals.  

- gamify the experience by creating challenges or goals that reward users for achieving specific milestones. 

4) Emphasize sleep tracking. Developing sleep tracking features and providing guidance on improving sleep quality, given the correlation observed between sedentary time and poor sleep quality.   

5) Bellabeat can encourage people to go to sleep earlier to get adequate amount and good quality of sleep by providing reminders and notifications:  

- set a bedtime reminder: Fitness trackers can be set to remind users to go to bed at a certain time each night. This can help establish a regular sleep schedule and promote healthier sleep habits.  

- monitor sleep patterns: Fitness trackers can track sleep patterns and provide insights into the quality and duration of sleep. 

- personalized recommendations for improving sleep habits. This might include suggestions for adjusting bedtime routines, reducing caffeine consumption, or increasing physical activity during the day.  

6) Knowing that Tuesday is a popular workout day, Bellabeat could provide personalized workout recommendations for users based on their fitness goals, offer Tuesday-specific workouts to encourage users to stick to their routine, create challenges or competitions specifically for Tuesdays to encourage users to work out and stay motivated.  

7) Since Saturday is the day users get the most sleep in a week, Bellabeat could offer tips and guidance to help users maintain good sleep habits throughout the week and improve sleep quality.  

8) Promote weight management: Given that very few users report weight-related information, Bellabeat could focus on promoting the benefits of weight management and highlight how its products can help users monitor and track their weight goals.  

